#
# ~/.bashrc
#

# Setup lucky core

export LUCKY_DIR="%%LUCKY_DIR%%"
export PATH=$PATH:$LUCKY_DIR

# Load up each module

for script in $(find "$LUCKY_DIR/mods-enabled" -maxdepth 1 -name "*.sh" 2>/dev/null | sort); do
    # NOTE: Each subscript should decide if it needs to be run in non-interactive
    source $script
done

