(xbindkey '("XF86AudioRaiseVolume")  "amixer set Master 3%+ unmute")
(xbindkey '("XF86AudioLowerVolume")  "amixer set Master 3%- unmute")
(xbindkey '("XF86AudioMute")         "amixer set Master toggle")
(xbindkey '("XF86MonBrightnessUp")   "xbacklight -inc 5")
(xbindkey '("XF86MonBrightnessDown") "xbacklight -dec 5")
